### ISSUE TITLE
Need help with setup

### ISSUE THREAD

**Issue by ghost** [crisap94/MHZ19#3]
I have just got my sensor and after uploading the example nothing works. I dont think it is my sensor or arduino, so i think the library needs updating or something. The sensor responds to none of the functions used in the code. Help me pleeeease!!! I really hope my sensor works.

**Comment by crisap94** [comment]
Hey.... Welll... the sensor Works, Calm down, the example is outdated... As i forked the library and implemented new features but the owner did not like it.... i will upload the exaple code soon.

**Comment by crisap94** [comment]
Example updated and Readme updated.... se last changes from the library to know how to use it.

**Comment by ghost** [comment]
wow thanks for the quick fix!

**Comment by ghost** [comment]
The new code works and is uploaded to my arduino and is connected to the sensor but after 10 minutes of warming the status is still 0. Is my sensor broken? am i missing something? does it take longer to warm up?

**Comment by Kumalix** [comment]
I have the same problem. After 1 hour it is still warming up?
Is this a liberary issue? or wiring?

**Comment by ghost** [comment]
I removed the warming loop and replaced it with a loop that counts down from 100. i have found that 100 seconds is enough time for it to warm up and function properly.


[Mh-Z19_working.zip](https://github.com/crisap94/MHZ19/files/3063650/Mh-Z19_working.zip)
