### ISSUE TITLE
fatal error: avr/interrupt.h: No such file or directory

### ISSUE THREAD

**Issue by Kumalix** [crisap94/MHZ19#4]
Hi,

I have used this liberary for my mhz19 sensor.
Now somtimes i get -1 PPM reading.
So checked and updated today this liberary.
But now i get the error: fatal error: avr/interrupt.h: No such file or directory

Can you help me? 

Arduino:1.8.8 (Mac OS X), Board:"ESP32 Dev Module, Disabled, Default, 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

Meerdere bibliotheken gevonden voor "MHZ19.h"
Gebruikt: /Users/nermin/Dropbox/Arduino/libraries/MHZ19-master
/Users/nermin/Dropbox/Arduino/libraries/SoftwareSerial-master/SoftwareSerial.cpp:41:27: fatal error: avr/interrupt.h: No such file or directory
Niet gebruikt: /Users/nermin/Dropbox/Arduino/libraries/MHZ19-60c76668598e331fde62134662fc486b6bd27e24
compilation terminated.
Niet gebruikt: /Users/nermin/Dropbox/Arduino/libraries/MH-Z19
exit status 1
Fout bij het compileren voor board ESP32 Dev Module

**Comment by crisap94** [comment]
I strongly recommend you to use [PlatformIO](https://platformio.org/platformio-ide), it has better indexing of the files, and the library is compiled with PlatformIO too.

Let me know if you have any comment.
